version: '3.5'

volumes:
    local_postgres_data: {}

services:
    postgres:
        image: postgres:latest
        container_name: pg-docker
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - ./db/postgres.conf:/etc/postgresql/postgresql.conf
            - ./db/data:/var/lib/postgresql/data
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        restart: always
           
